version: "3.1"

services:
  mongo:
    image: mongo:6.0.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: SUPER_secret1029
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: SUPER_secret1029
      ME_CONFIG_MONGODB_URL: mongodb://admin:SUPER_secret1029@mongo:27017/

volumes:
  mongo-data:
    driver: local
